### ISSUE TITLE
Stworzenie projektu strony w gimpie 

### ISSUE THREAD

**Issue by mk1808** [mk1808/webProject#2]

**Comment by mk1808** [comment]
![uklad](https://user-images.githubusercontent.com/37344587/47602800-fa99ff00-d9e3-11e8-8d64-d42b2dd34a95.png)

**Comment by mk1808** [comment]
#niemampojeciacorobie
#sadreactionsonly

**Comment by mk1808** [comment]
https://coolors.co/

**Comment by mk1808** [comment]
![uklad - kopia](https://user-images.githubusercontent.com/37344587/47603089-48643680-d9e7-11e8-89ae-e85655e4ca2a.png)

**Comment by marqos12** [comment]
![wyglad-1](https://user-images.githubusercontent.com/17620731/47608549-bcc2c800-da2f-11e8-92b4-04efb5a6687d.png)
