### ISSUE TITLE
Tworzenie nowego quizu 

### ISSUE THREAD

**Issue by mk1808** [mk1808/webProject#25]
Utworzyć nowy quiz z wszystkimi danymi

Todo wymyślić pola

**Comment by marqos12** [comment]
nazwa
kategoria
//autor
ilość pytań
czy wielokrotnego wyboru
czy każde na osobnej stronie
    --jeśli tak to czy można przewijać do tyłu
czy czas ograniczony
   --ograniczenie czasu na pytanie czy na cały test
   ----ile tego czasu
?? czy dostępny dla niezalogowanych ??
