### ISSUE TITLE
Tworzenie pytania 

### ISSUE THREAD

**Issue by mk1808** [mk1808/webProject#28]

**Comment by marqos12** [comment]
konversja bloba na plik   https://stackoverflow.com/questions/27553617/convert-blob-to-file/27565109
konversja pliku na bloba https://stackoverflow.com/questions/45530752/getting-image-from-api-in-angular-4-5


chodzi o to, żeby wysłać do bazy bloba i potem tego bloba wyświetlić już w quizie
