### ISSUE TITLE
Potrzebne endpointy

### ISSUE THREAD

**Issue by mk1808** [mk1808/webProject#35]
Do zrobienia:

zwroc poprawne odpowiedzi dla pytania
zwroc pytania dla quizu z poprawnymi odpowiedziami

skasuj pytanie
skasuj quiz
Lista quizow
Lista odpowiedzi czlowieczka
Info o quizie

Już są

1. logowanie (autoryzacja)
2. Rejestracja
3. edycja danych
4. Sprawdzenie odpowiedzi
5. Dodawanie quizu
6. Dodawanie pytania
7. lista quizów dla autora
8. Zwróć detale quizu
9. zwróć kierunki
10. lista pytań z odpowiedziami dla danego quizu
11. zwróć pojedyncze pytanie z odpowiedziami
12. zwróć kategorie
13. lista quizów dla kierunku
14. ostatni wynik dla quizu o id tego uzytkownika
15. uaktualnij quiz
16. uaktualnij pytanie
17. sprawdz odp i zapisz wynik
18. lista pytań dla danego quizu w bazie
19. losowe pytania do quizu
20. zatwierdzenie quizu
21. anulowanie quizu
22. dodanie pytania kateggoryzowanego
23. zwrócenie listy kategorii (kategoryzowane)
24. zwrócenie pytań z kategorii
25. zwrocenie wszystkich pytań kategoryzowanych z podziałem na kategorie
26. dodanie nowego wpisu subject_question
27. lista pytań z poprawnymi odpowiedziami dla quizu o id

**Comment by marqos12** [comment]
CheckAnswers

adres: http://localhost/web/web/api/controllers/checkAnswers.php
typ: POST
przyjmuje: Lista id pytań z tablicami id odpowiedzi i wartościami odpowiedzi
przykłąd wejścia: 

> 
> {
> 	"questions":[
> 		{
> 			"id":"1",
> 			"answers":[
> 				{
> 				"id": "1",
> 				"value": "0"
> 				},
> 				{
> 				"id": "2",
> 				"value": "1"
> 				},
> 				{
> 				"id": "3",
> 				"value": "0"
> 				},
> 				{
> 				"id": "4",
> 				"value": "0"
> 				}
> 			]
> 		},
> 		{
> 			"id":"4",
> 			"answers":[

odpowiada: JSON z ilością wszystkich pytań i poprawnie odpowiedzianych pytań
przykład odpowiedzi:

> {
>     "total": 4,
>     "true": 4
> }

**Comment by marqos12** [comment]
GetQuestionsAndAnswers

adres: http://localhost/web/web/api/controllers/getQuestionsQndAnswers.php
typ: GET
przyjmuje: -
przykłąd wejścia: -
odpowiada: JSON z wszystkimi pytaniami z bazy wraz z odpowiedziami
przykład odpowiedzi:

**Comment by marqos12** [comment]
CreateUser

adres: http://localhost/web/web/api/controllers/auth/createUser.php
typ: POST
przyjmuje: Json z danymi użytkownika
przykłąd wejścia: 
>{
 >   "name" : "Mike2",
  >  "surname" : "Dalisay2",
   > "email" : "mike2@codeofaninja.com",
    >"password" : "555",
    >"role" : "21"
>}
odpowiada: komunikat albo że dodano albo że nie dodano
przykład odpowiedzi:
>{
>    "message": "User was created."
>}

**Comment by marqos12** [comment]
Login

adres: http://localhost/web/web/api/controllers/auth/login.php
typ: POST
przyjmuje: JSON z emailem i wpisanym hasłem
przykłąd wejścia: 

> {
>     "email" : "mike@codeofaninja.com",
>     "password" : "555"
> }

odpowiada: JSON z wiadomością i tokenem jwt
przykład odpowiedzi:
![obraz](https://user-images.githubusercontent.com/17620731/48960576-f246cc80-ef6d-11e8-8aec-28bbb5723f45.png)

**Comment by marqos12** [comment]
UpdateUser

adres: http://localhost/web/web/api/controllers/auth/updateUser.php
typ: POST
przyjmuje: JSON z nowymi danymi użytkownika
przykłąd wejścia: 
![obraz](https://user-images.githubusercontent.com/17620731/48960695-37b7c980-ef6f-11e8-84ed-0c51d680820b.png)

odpowiada: JSON z wiadomością i tokenem
przykład odpowiedzi:
![obraz](https://user-images.githubusercontent.com/17620731/48960706-4dc58a00-ef6f-11e8-9a45-acb0d2edf959.png)

**Comment by marqos12** [comment]
Wzór opisu 


Nazwa

adres:
typ:
przyjmuje: -
przykłąd wejścia: -
odpowiada: JSON
przykład odpowiedzi:

**Comment by marqos12** [comment]
CreateSubject

adres: http://localhost/web/web/api/controllers/quiz/createSubject.php
typ: POST
przyjmuje: JSON z nowym quizem
przykłąd wejścia: 
![obraz](https://user-images.githubusercontent.com/17620731/48985075-4aafd280-f104-11e8-96d7-188ae8e8832e.png)

odpowiada: JSON z potwierdzeniem utworzenia

TODO:  potwierdzenie uwierzytelnienia

**Comment by marqos12** [comment]
CreateQuestion

adres: http://localhost/web/web/api/controllers/question/createQuestion.php
typ: POST
przyjmuje: -Json z nowym pytaniem
przykłąd wejścia: 
![obraz](https://user-images.githubusercontent.com/17620731/49072618-e6d6f800-f230-11e8-8255-63b48bc28279.png)

odpowiada: JSON z potwierdzeniem

TODO: potwierdzenie uwierzytelnienia

**Comment by marqos12** [comment]
GetQuizListForAuthor

adres: http://localhost/web/web/api/controllers/quiz/getQuizListForAuthor.php
typ: GET
przyjmuje: Json z id autora dla którego pobieramy liste quizów
![image](https://user-images.githubusercontent.com/17620731/49227915-84295c00-f3ea-11e8-9da5-5c28aa8def40.png)

**Comment by marqos12** [comment]
getQuizDetails

adres: http://localhost/web/web/api/controllers/quiz/getQuizDetails.php
typ: GET
przyjmuje: id j/w
odpowiada: JSON z całym obiektem klasy subject
przykład odpowiedzi:
![obraz](https://user-images.githubusercontent.com/17620731/49247417-82c25880-f417-11e8-9b98-3044e238dfaa.png)

**Comment by marqos12** [comment]
getCoursesList

adres: http://localhost/web/web/api/controllers/dictionary/getCoursesList.php
typ: GET
![obraz](https://user-images.githubusercontent.com/17620731/49280062-6c54e500-f489-11e8-92e0-573f1627428b.png)

**Comment by marqos12** [comment]
getQuestionsWithAnswersForQuiz

adres: http://localhost/web/web/api/controllers/question/getQuestionsWithAnswersForQuiz.php
typ: GET
dostaje: id z numerem quizu
zwraca: tablice pytań z odpowiedziami iterere
![obraz](https://user-images.githubusercontent.com/17620731/49285758-a8437680-f498-11e8-8353-86eac53a2b5c.png)

**Comment by marqos12** [comment]
getQuestionWithAnswer

adres: http://localhost/web/web/api/controllers/question/getQuestionWithAnswers.php
typ: GET
![obraz](https://user-images.githubusercontent.com/17620731/49287197-d4f98d00-f49c-11e8-903b-3c3c0022812c.png)

**Comment by marqos12** [comment]
getCategories

adres: http://localhost/web/web/api/controllers/dictionary/getCategories.php
typ: GET

![obraz](https://user-images.githubusercontent.com/17620731/49287482-eb541880-f49d-11e8-9298-9ee90c23830b.png)

**Comment by marqos12** [comment]
getQuizListForCourse

adres: http://localhost/web/web/api/controllers/quiz/getQuizForCourse.php
typ: GET
![obraz](https://user-images.githubusercontent.com/17620731/49314017-6b53a000-f4e9-11e8-9f18-5355bf55c43c.png)

**Comment by marqos12** [comment]
getUserResultForQuiz

adres: http://localhost/web/web/api/controllers/quiz/getUsersResultForQuestion.php
typ: GET

![obraz](https://user-images.githubusercontent.com/17620731/49315140-e8ccdf80-f4ec-11e8-88e8-043a9d49a8d2.png)

**Comment by marqos12** [comment]
UpdateSubject

adres: http://localhost/web/web/api/controllers/quiz/updateSubject.php
typ: POST

![obraz](https://user-images.githubusercontent.com/17620731/50042040-4c631b00-005e-11e9-8aa7-a90dfbaf5f67.png)

**Comment by marqos12** [comment]
Update question with answers

16. uaktualnij pytanie

adres: http://localhost/web/web/api/controllers/question/updateQuestion.php

![obraz](https://user-images.githubusercontent.com/17620731/50043350-cf8e6c00-0072-11e9-9bcf-7a86435c7ab3.png)

**Comment by marqos12** [comment]
CheckAnswerSaveResult

17. sprawdz odp i zapisz wynik

adres: http://localhost/web/web/api/controllers/question/checkAnswers.php
typ: POST
![obraz](https://user-images.githubusercontent.com/17620731/50045318-fc517c00-0090-11e9-9ff1-73684c241eb9.png)

**Comment by marqos12** [comment]
GetRandomQuestionForQuiz

19. losowe pytania do quizu

adres: http://localhost/web/web/api/controllers/question/getRandomQuestionsForQuiz.php?id=2
typ: GET

![image](https://user-images.githubusercontent.com/17620731/50219701-56ec2000-0390-11e9-9a15-66d5d62c74aa.png)

**Comment by marqos12** [comment]
acceptSubject
20. zatwierdzenie quizu

typ: POST
adres: http://localhost/web/web/api/controllers/quiz/acceptSubject.php


przyjmuje: JSON z id tematu i JWT

**Comment by marqos12** [comment]
cancelSubject

21. anulowanie quizu
typ: POST
adres: http://localhost/web/web/api/controllers/quiz/cancelSubject.php

przyjmuje: JSON z id tematu i JWT

**Comment by marqos12** [comment]
createCategorysedQuestions
22. dodanie pytania kateggoryzowanego

adres: http://localhost/web/web/api/controllers/question/createCategorysedQuestion.php
typ: POST

przyjmuje: to samo co zwykłe tworzenie pytania, czyli pytanie z tablicą odpowiedzi i JWT, ale bez idSubject

**Comment by marqos12** [comment]
getDemoId

23. zwrócenie id quizu demonstracyjnego

adres: http://localhost/web/web/api/controllers/demo/getDemoId.php
typ: POST

przyjmuje: nic, zwraca id

**Comment by marqos12** [comment]
23 zwrócenie listy kategorii (kategoryzowane)

adres: http://localhost/web/web/api/controllers/categorised/getCategoriesList.php
typ POST
nic nie przyjmuje, zwraca tablicę stringów

**Comment by marqos12** [comment]
24 zwrócenie pytań z kategorii


adres: http://localhost/web/web/api/controllers/categorised/getQuestionsForCategory.php
przyjmuje json z id = nazwa kategorii i jwt

**Comment by marqos12** [comment]
25. zwrócenie wszystkich pytań kategoryzowanych z podziałem na kategorie

http://localhost/web/web/api/controllers/categorised/getQuestionsForAllCtegories.php
typ post, 
przyjmuje jwt, zwraca tablicę obiektów z nazwami kategorii i tablicami pytań

**Comment by marqos12** [comment]
26. dodanie nowego wpisu subject_question

adres: http://localhost/web/web/api/controllers/categorised/createSubjectQuestionForQuiz.php

przyjmuje idSubject, category, number i klasycznie jwt, zwraca status i przy powodzeniu id nowego wpisu w bazie

**Comment by marqos12** [comment]
27. lista pytań z poprawnymi odpowiedziami dla quizu o id 

adres: http://localhost/web/web/api/controllers/question/getAnswerWithStatusForQuiz.php
typ: POST

przyjmuje id i jwt
